### ISSUE TITLE
MPEG-DASH support

### ISSUE THREAD

**Issue by AlexRevin** [Viblast/hls-proxy#1]
It seems like not much needs to be added, but it really would be awesome

**Comment by svetlin-mladenov** [comment]
Yeah, I was meaning to do that. Thank you for reminding me.

You can find the project here - https://github.com/Viblast/dash-proxy. It is in a different repo because it works in a slightly different manner and doesn't rely on twisted but instead uses requests.

Also MPEG-DASH is a much wider standard that has many different ways of expressing the MPD (things like on-demand,live, dynamic profiles and so on). dashproxy currently supports only MPDs based on SegmentTimelines.

**Comment by AlexRevin** [comment]
Thanks a lot for pointing out!
